name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install deps
        run: npm ci

      # Vitest uses mongodb-memory-server so no DB secrets needed.
      - name: Run tests (Vitest)
        env:
          NODE_ENV: test
          JWT_SECRET: dummy_secret_for_ci
        run: npm test
